[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "COREPACK_INTEGRITY_KEYS=0 corepack enable",
  "COREPACK_INTEGRITY_KEYS=0 pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[phases.build.env]
NEXT_TELEMETRY_DISABLED = "1"

[start]
cmd = "pnpm start"
